application: put your own google app id here
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest
- name: jinja2
  version: latest

builtins:
- remote_api: on
- datastore_admin: on
- appstats: on
- deferred: on

inbound_services:
- mail
- channel_presence
- warmup

admin_console:
  pages:
  - name: Edit Domains
    url: /account/admin/editdomains
  - name: Edit Pages
    url: /account/admin/editpages

handlers:
- url: /.*
  script: main.application